feat: 🎸 add checks to check if asset/account exists
PolymeshAssociation/polymesh-private-sdk pull request #32
Opened 2024-08-02 14:28 UTC by sansan

### Description

adds additional validation checks:
- checks if sending CA exists
- checks if receiving CA exists
- checks if provided confidential accounts exist

### JIRA Link

https://polymesh.atlassian.net/browse/DA-1233

### Checklist

- [x] Updated the Readme.md (if required) ?

2024-08-02 14:48 UTC, prashantasdeveloper requested changes

2024-08-02 14:48 UTC, prashantasdeveloper commented on src/api/procedures/moveFunds.ts
> +      message: 'One or more of the specified Confidential Assets do not exist',
You can filter out the account and pass as data

2024-08-02 14:54 UTC, polymath-eric reviewed
I think `data` is something we should try to add in when we can. I find it helpful for debugging. Tests don't need to be updated, the `code` and `message` assertions should be enough.

2024-08-02 14:54 UTC, polymath-eric commented on src/api/procedures/moveFunds.ts
> +      message: 'The receiving Confidential Account does not exist',
```suggestion
      message: 'The receiving Confidential Account does not exist',
      data: { receivingAccount: receivingAccount.publicKey }
```

Same with the sender account error.

If the error happens its nice to have the actual account.

2024-08-02 14:54 UTC, polymath-eric commented on src/api/procedures/moveFunds.ts
> +    return confidentialAsset.exists();
(optional) I think it would be nice to report back the exact assets that don't exist in `data`. If the id gets grouped into the result it should be

```suggestion
    const exists = await confidentialAsset.exists()
    
    return { assetId: asset.id, exists }
```
    
Then
```ts
    const notFoundAssets = assetExists.filter(({ exists }) => exists)    
    if(notFoundAssets.length) {
    ...
    data: notFoundAssets.map(({ assetId }) => assetId)
 ```

2024-08-06 11:35 UTC, prashantasdeveloper approved these changes

2024-08-06 11:47 UTC, merged

2024-08-06 11:52 UTC, polymath-eric commented
:tada: This PR is included in version 2.0.0-alpha.3 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-private-sdk/v/2.0.0-alpha.3)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-private-sdk/releases/tag/v2.0.0-alpha.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-11-15 15:47 UTC, polymath-eric commented
:tada: This PR is included in version 2.0.0-beta.1 :tada:

The release is available on:
- [npm package (@beta dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-private-sdk/v/2.0.0-beta.1)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-private-sdk/releases/tag/v2.0.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-11-15 17:58 UTC, polymath-eric commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-private-sdk/v/2.0.0)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-private-sdk/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: