fix: 🐛 getTransactionHistory query
PolymeshAssociation/polymesh-private-sdk pull request #8
Opened 2024-03-06 16:13 UTC by sansan

### Description

### Breaking Changes

### JIRA Link

### Checklist

- [ ] Updated the Readme.md (if required) ?

2024-03-07 13:47 UTC, VictorVicente requested changes

2024-03-07 13:47 UTC, VictorVicente commented on src/api/entities/confidential/ConfidentialAccount/index.ts
> +    console.log(nodes);
Please remove this log

2024-03-07 13:47 UTC, polymath-eric approved these changes

2024-03-07 13:48 UTC, polymath-eric reviewed
LGTM except the console.log Victor mentioned

2024-03-08 11:13 UTC, merged

2024-03-08 11:24 UTC, polymath-eric commented
:tada: This PR is included in version 1.0.0-alpha.8 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/@polymeshassociation/polymesh-private-sdk/v/1.0.0-alpha.8)
- [GitHub release](https://github.com/PolymeshAssociation/polymesh-private-sdk/releases/tag/v1.0.0-alpha.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: